steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/usuba', '-f', './rust/usuba/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/usuba']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'labs', '--image', 'gcr.io/$PROJECT_ID/usuba', '--region', 'us-central1']
images:
- gcr.io/$PROJECT_ID/usuba
options:
  logging: CLOUD_LOGGING_ONLY