[package]
name = "usuba-compat"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-component-bindgen = { workspace = true }
wit-bindgen = { workspace = true }
wasmtime-environ = { workspace = true,  features = ["component-model", "compile"] }