name: Deploy to Docker Hub

on:
  push:
    # branches:
    # - main
    paths:
      - typescript/packages/planning-server/**/*
      - .github/workflows/planning-server-dockerhub.yml
  pull_request:

  workflow_dispatch:
    inputs:
      push:
        description: "Push docker image"
        required: false
        type: boolean
        default: false

env:
  PUSH: ${{ ( github.ref == 'refs/heads/main' && github.event_name == 'push' ) || github.event.inputs.push }}
  WORKING_DIRECTORY: typescript/packages/planning-server
  DENO_VERSION: 1.46.3
  TS_ENTRYPOINT: src/index.ts
  ARTIFACT_NAME: planning-server
  CONTAINER_PORT: 8000

defaults:
  run:
    working-directory: typescript/packages/planning-server # annoying necessity as env vars are not available in defaults

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute short hash
        id: short_hash
        run: echo "short_hash=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Get env vars
        id: vars
        run: |
          echo "PUSH=${{ env.PUSH }}" >> $GITHUB_OUTPUT
          echo "WORKING_DIRECTORY=${{ env.WORKING_DIRECTORY }}" >> $GITHUB_OUTPUT
          echo "DENO_VERSION=${{ env.DENO_VERSION }}" >> $GITHUB_OUTPUT
          echo "TS_ENTRYPOINT=${{ env.TS_ENTRYPOINT }}" >> $GITHUB_OUTPUT
          echo "ARTIFACT_NAME=${{ env.ARTIFACT_NAME }}" >> $GITHUB_OUTPUT
          echo "CONTAINER_PORT=${{ env.CONTAINER_PORT }}" >> $GITHUB_OUTPUT
    outputs:
      PUSH: ${{ steps.vars.outputs.PUSH }}
      WORKING_DIRECTORY: ${{ steps.vars.outputs.WORKING_DIRECTORY }}
      DENO_VERSION: ${{ steps.vars.outputs.DENO_VERSION }}
      TS_ENTRYPOINT: ${{ steps.vars.outputs.TS_ENTRYPOINT }}
      ARTIFACT_NAME: ${{ steps.vars.outputs.ARTIFACT_NAME }}
      CONTAINER_PORT: ${{ steps.vars.outputs.CONTAINER_PORT }}
      SHORT_HASH: ${{ steps.short_hash.outputs.short_hash }}

  test:
    continue-on-error: true # TODO: remove this when tests are validated
    name: Test under Deno
    runs-on: ubuntu-latest
    steps:
      - name: cache deno installation and deno.land dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*.ts') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno/deps/https/deno.land

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - run: deno run test

  compile:
    # supported deno architectures:
    # x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin, aarch64-apple-darwin
    strategy:
      fail-fast: false
      matrix:
        include:
          - host_os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            os: linux
            arch: x86_64

          - host_os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            os: linux
            arch: aarch64

          - host_os: windows-latest
            target: x86_64-pc-windows-msvc
            os: windows
            arch: x86_64

          - host_os: macos-latest
            target: x86_64-apple-darwin
            os: macos
            arch: x86_64

          - host_os: macos-latest
            target: aarch64-apple-darwin
            os: macos
            arch: aarch64

    runs-on: ${{ matrix.host_os }}
    env:
      DESTINATION: dist/bin/${{ matrix.os }}/${{ matrix.arch }}/$ARTIFACT_NAME
    name: Compile ${{ matrix.os }} ${{ matrix.arch }} binary
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache deno installation and deno.land dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*.ts') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno/deps/https/deno.land

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Compile Deno entrypoint
        run: deno compile --output ${{ env.DESTINATION }} --target ${{ matrix.target }} --allow-all ${{ env.TS_ENTRYPOINT }}

      - name: List all files recursively in dist directory (Unix or macOS)
        if: ${{ runner.os != 'Windows' }}
        run: ls -R $(dirname ${{ env.DESTINATION }})

      - name: List all files recursively in dist directory (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: dir $(dirname ${{ env.DESTINATION }})

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: planning-server-${{ matrix.target }}
          path: typescript/packages/planning-server/${{ env.DESTINATION }}${{ runner.os == 'Windows' && '.exe' || '' }}

  docker:
    needs:
      - setup
    name: Build Docker image${{ needs.setup.outputs.PUSH && ' and push to Docker Hub' || '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      PUSH: ${{ needs.setup.outputs.PUSH }}
      WORKING_DIRECTORY: ${{ needs.setup.outputs.WORKING_DIRECTORY }}
      DENO_VERSION: ${{ needs.setup.outputs.DENO_VERSION }}
      TS_ENTRYPOINT: ${{ needs.setup.outputs.TS_ENTRYPOINT }}
      ARTIFACT_NAME: ${{ needs.setup.outputs.ARTIFACT_NAME }}
      CONTAINER_PORT: ${{ needs.setup.outputs.CONTAINER_PORT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # https://github.com/docker/setup-qemu-action

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # https://github.com/docker/setup-buildx-action
        with:
          driver-opts: network=host # required for local registry. see: https://docs.docker.com/build/ci/github-actions/local-registry/

      - name: Install cosign
        uses: sigstore/cosign-installer@v3 # https://github.com/sigstore/cosign-installer

      # - name: Log in to Docker Hub
      #   if: ${{ env.PUSH }}
      #   uses: docker/login-action@v3 # https://github.com/docker/login-action
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute full image tag path
        id: image_path
        run: |
          echo "IMAGE_PATH=localhost:5000/${{ secrets.DOCKERHUB_USERNAME || 'local' }}/${{ needs.setup.outputs.ARTIFACT_NAME }}:${{ needs.setup.outputs.SHORT_HASH }}" >> $GITHUB_ENV
          echo "IMAGE_PATH=$IMAGE_PATH" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v6 # https://github.com/docker/build-push-action
        name: Build and locally push Docker image
        with:
          build-args: |
            DENO_VERSION=${{ needs.setup.outputs.DENO_VERSION }}
            TS_ENTRYPOINT=${{ needs.setup.outputs.TS_ENTRYPOINT }}
            ARTIFACT_NAME=${{ needs.setup.outputs.ARTIFACT_NAME }}
          context: ${{ needs.setup.outputs.WORKING_DIRECTORY }}
          push: true
          load: true # load the image into the Docker daemon
          tags: |
            ${{ steps.image_path.outputs.IMAGE_PATH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Launch image in local registry
        run: docker run -d --rm -p $CONTAINER_PORT:$CONTAINER_PORT $IMAGE_PATH
      - name: Container identity
        id: container_id
        run: |
          echo "CONTAINER_ID=$(docker ps -q --filter "ancestor=$IMAGE_PATH")" >> $GITHUB_ENV
          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_OUTPUT

      - name: Wait until the container port is open
        run: |
          for i in {1..10}; do
            if nc -z localhost $CONTAINER_PORT; then
              echo "Server is up"
              break
            fi
            sleep 1
          done
      - name: Verify curl is installed
        run: curl --version
      - name: Test the container
        id: test
        run: |
          curl 'http://localhost:8000/' \
          -H 'Content-Type: application/json' \
          --data-raw $'{"action":"create","system":"You say 42 to any message","message":"What is the meaning of life?","activeTools":[]}'
        continue-on-error: true
      - name: Get container logs
        if: steps.test.outcome == 'failure'
        run: docker logs $CONTAINER_ID
      - name: Stop the container
        run: docker stop $CONTAINER_ID
